services:
  - docker
  
script:
  - docker build -t test-image:test .
  - docker run -d -ti --name test -p 80:80 -p 8004:8004 -p 443:443 test-image:test
  - travis_wait 35 sleep 30m
  - docker logs test
  - curl -sSf http://localhost/ocpu/library/flycircuit/R/
